### ISSUE TITLE
Curam SPs - Get production version of each SP into repo

### ISSUE THREAD

**Issue by marthabmd** [dchealthlink/CuramSPUAT#2]
Please create a new repo for the production SPs, and let Marty know the name so she can include in our team and ZenHub board

**Comment by pegasus4848** [comment]
8/4/2018: Waiting to successfully compile and test each procedure before placing it in the repository.
     1. The get_integrated_case_by_caseref procedure is not compiling. Mamatha sent me code, but it is the body of the procedure run with one IC.  I will retry to incorporate it into a procedure.
     2. Based on data from Tom, I have found problems with PROCEDURE "CAL_BODY_MB":
          a. At least some cases resulting in "NO_DATA_FOUND" seem to be for individuals who are not the primary. Searching for the primary results in found data. Waiting to see if this is useful to Tom, before researching other such cases.
          b. The code would occasionally blow up because we assumed there would be an one record in the APPLICATIONCASE table for the given person (name, dob,ssn), but in some cases where multiple records were returned, one of them had no corresponding APPLICATIONCASE record and so threw an oracle error. Fixed and tested.
          c. There are some cases where more than on APPPLICATIONCASE records are found, when only one is expected. Should we generate multiple records, one for each returned APPLICATION record?

**Comment by pegasus4848** [comment]
Waiting for latest test of all SPs (including two new ones).
